[tool.poetry]
name = "charm-dev"
version = "0.1.0"
description = ""
authors = ["MaryannGitonga <naygitonga4@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ops = ">=2.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
